# Generated by Django 3.1.3 on 2020-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contractor_name', models.CharField(max_length=255)),
                ('contractor_surname', models.CharField(max_length=255)),
                ('contractor_patronymic', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('adress', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('executor_name', models.CharField(max_length=255)),
                ('executor_surname', models.CharField(max_length=255)),
                ('executor_patronymic', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('id_contractor', models.IntegerField()),
                ('registar_surname', models.CharField(max_length=255)),
                ('registar_name', models.CharField(max_length=255)),
                ('registar_patronymic', models.CharField(max_length=255)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('uodate_date', models.DateTimeField(auto_now=True)),
                ('id_executor', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
