# Generated by Django 3.1.3 on 2020-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0002_auto_20201204_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='doc_uodate_date',
            new_name='doc_update_date',
        ),
    ]
