# Generated by Django 3.1.3 on 2020-12-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0003_auto_20201204_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contr',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='dep',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='contr',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='apartment',
            field=models.CharField(max_length=255, verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='contr_name',
            field=models.CharField(max_length=255, verbose_name='Имя контрагента'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='contr_patronymic',
            field=models.CharField(max_length=255, verbose_name='Отчество контрагента'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='contr_surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия контрагента'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='telephone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contr',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='executor_name',
            field=models.CharField(max_length=255, verbose_name='Имя исполнителя'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='executor_patronymic',
            field=models.CharField(max_length=255, verbose_name='Отчество исполнителя'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='executor_surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия исполнителя'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='telephone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id_contr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edms.contr', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edms.dep', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='reg_name',
            field=models.CharField(max_length=255, verbose_name='Имя регистратора'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='reg_patronymic',
            field=models.CharField(max_length=255, verbose_name='Отчество регистратора'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='reg_surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия регистроторав'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
