# Generated by Django 3.1.3 on 2020-12-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0004_auto_20201214_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contr',
            name='telephone',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='telephone',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id_contr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='edms.contr', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='id_executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='edms.dep', verbose_name='Исполнитель'),
        ),
    ]
